# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeefitMsc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase', '>= 2.5.1'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
  # Pods for BeefitMsc

  target 'BeefitMscTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
